# Configuration pour les scripts de Didier
SOUNDBOKS_MAC="00:07:80:E0:3F:F0"

# Adresse IP sur laquelle le serveur web de Didier doit écouter.
# "0.0.0.0" est recommandé pour écouter sur toutes les interfaces réseau.
SERVER_HOST="0.0.0.0"